"use strict";
console.log("First Program");
console.log("good" + " morning");
var light = true;
var firstName = "deepak";
var phoneNumber = "8400000166";
var grade = 8.5;
console.log("hi " + firstName + " your grade is " + grade + " " + light);
firstName = "ranjan";
grade = 6;
console.log("hi " + firstName + " your grade is " + grade);
firstName = "Vikas";
grade = 9;
console.log("hi " + firstName + " your grade is " + grade);
